### ISSUE TITLE
bert-serving-start -model_dir ...    error

### ISSUE THREAD

**Issue by lyshello123** [hanxiao/bert-as-service#241]
![image](https://user-images.githubusercontent.com/25859365/52946153-51ba4a00-33ae-11e9-8c5e-602ff6522f7a.png)

TypeError: 'NoneType' object is not iterable

My environment is win10+tensorflow 1.12, can you give me some help? thank you!

**Comment by valavakilian** [comment]
Hi . I have the same I issue. Can you please share how you fixed it @lyshello123 ?

**Comment by valavakilian** [comment]
Sorry. Solved it . I was using a local path and running. But the program needs the full path of the files .
My apologies and thank you for the amazing tool.

**Comment by malsing** [comment]
Could you please explain what you replaced the path with? I completed my path for the model with /Users/USERNAME/model/ but still get this same error.

**Comment by DavenH** [comment]
I get this error with a fine-tuned model, but not the original.

**Comment by trungpham10** [comment]
@malsing have you solved the problem? I have the same issue, thanks!

**Comment by malsing** [comment]
It was an issue with my path itself... I needed to end it without the final "/":  /Users/USERNAME/model

**Comment by cpmss521** [comment]
Hi . I have the same problem, can  you share me how did you solve it

**Comment by trungpham10** [comment]
I use the following -model_dir "C:/bert_model/uncased_L-12_H-768_A-12/", make sure your path has no space too

**Comment by cpmss521** [comment]
thanks a lot ,it didn't work for me ,  i did it according to the readme,

**Comment by nomadavid9** [comment]
Still getting a "NoneType object is not iterable" error message 
my command call looks like:

bert-serving-start -model_dir /Users/MY_USERNAME/.../tmp/uncased_L-12_H-768_A-12 -num_worker=4

where the ... are just folders leading up to the tmp folder, grabbed directly from a pwd command
And MY_USERNAME is my actual username.

I have tried with and without the trailing "/"

**Comment by plutokevin** [comment]
Hi . I used to have the same issue ,but I solved it. I find my model path is wrong and I changed it，Then the problem is solved. I hope it can help you. : )

**Comment by panteaHK** [comment]
Hello, I have used as suggested the absolute path without `\` at the end:
`bert-serving-start -model_dir=%AbsolutePath% -max_seq_len 20 -num_worker=5`
However, I am still getting the same error. I downgraded tensorflow and it also did not work.
